### PR TITLE
debian release 0.4-1

### PR DESCRIPTION
**Pull request by barak**
A few tweaks to debian/* and some spelling corrections to upstream bits.
(Let me know if I should do a debian release merging from a point above v0.4)

### CODE REVIEW

**Comment by xaionaro** [comment]
Huge thanks! Somehow I am ashamed of so many problems.

By the way. If you're going to push the new version of clsync to the Debian repositories, then can you wait 3 days? I need to fix two bugs and release version "0.4.2".

**Comment by barak** [comment]
Sorry too late, it's already uploaded.
(I usually push the debian/xxx tag as dput is running.)

Let me know when 0.4.1 is out and I'll upload that.

If you *really* don't want people to run 0.4, we could file a grave bug against it, which might dissuade them.

**Comment by xaionaro** [comment]
> Let me know when 0.4.1 is out and I'll upload that.

Ok, thanks :)

> If you really don't want people to run 0.4, we could file a grave bug against it, which might dissuade them.

No need. 0.4 better than the previous version, anyway.

**Comment by xaionaro** [comment]
@barak. I released v0.4.1. There's a lot of important bugfixes. Please push it to the Debian repositories if you have time.

https://github.com/xaionaro/clsync/releases/tag/v0.4.1

**Comment by barak** [comment]
Done.

There are build issues on autobuilders for some other architectures, which you can see here:
https://buildd.debian.org/status/package.php?p=clsync

**Comment by xaionaro** [comment]
Thanks! If I will fix the issues then will you able to re-push the clsync?

**Comment by barak** [comment]
Sure.

**Comment by xaionaro** [comment]
Unfortunately, it's pretty difficult to port clsync to Hurd right now. However seems I fixed clsync on Debian/kFreeBSD. I that possible to check building on Debian auto building system before a release? Or I just need to release 0.4.2 and fix new issues (if will be found) in 0.4.3?

**Comment by barak** [comment]
I think it would be okay to wait until the next natural release point.

**Pull request merged**
